<?php

namespace App\DataFixtures;

use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use App\Entity\Meet;

class MeetsFixtures extends Fixture implements OrderedFixtureInterface {

    public function getOrder() {
        return 2;
    }

    public function load(ObjectManager $manager) {

        $meetsList = array(
            array(
                'meet_name' => 'Mecz 1',
                'team_name_1' => 'Meksyk',
                'team_name_2' => 'RPA',
                'matchday_name' => 'Kolejka 1',
                'description' => 'Mistrzostwa Świata',
                'term' => 'czwartek, 11 czerwca',
                'position' => 1,
            ),
            array(
                'meet_name' => 'Mecz 2',
                'team_name_1' => 'Korea Południowa',
                'team_name_2' => 'Czechy',
                'matchday_name' => 'Kolejka 1',
                'description' => 'Mistrzostwa Świata',
                'term' => 'piątek, 12 czerwca',
                'position' => 2,
            ),

            array(
                'meet_name' => 'Mecz 3',
                'team_name_1' => 'Kanada',
                'team_name_2' => 'Bośnia i Hercegowina',
                'matchday_name' => 'Kolejka 1',
                'description' => 'Mistrzostwa Świata',
                'term' => 'piątek, 12 czerwca',
                'position' => 3,
            ),
            array(
                'meet_name' => 'Mecz 4',
                'team_name_1' => 'USA',
                'team_name_2' => 'Paragwaj',
                'matchday_name' => 'Kolejka 1',
                'description' => 'Mistrzostwa Świata',
                'term' => 'sobota, 13 czerwca',
                'position' => 4,
            ),
            array(
                'meet_name' => 'Mecz 5',
                'team_name_1' => 'Katar',
                'team_name_2' => 'Szwajcaria',
                'matchday_name' => 'Kolejka 1',
                'description' => 'Mistrzostwa Świata',
                'term' => 'sobota, 13 czerwca',
                'position' => 5,
            ),
            array(
                'meet_name' => 'Mecz 6',
                'team_name_1' => 'Brazylia',
                'team_name_2' => 'Maroko',
                'matchday_name' => 'Kolejka 1',
                'description' => 'Mistrzostwa Świata',
                'term' => 'niedziela, 14 czerwca',
                'position' => 6,
            ),
            array(
                'meet_name' => 'Mecz 7',
                'team_name_1' => 'Haiti',
                'team_name_2' => 'Szkocja',
                'matchday_name' => 'Kolejka 1',
                'description' => 'Mistrzostwa Świata',
                'term' => 'niedziela, 14 czerwca',
                'position' => 7,
            ),
            array(
                'meet_name' => 'Mecz 8',
                'team_name_1' => 'Australia',
                'team_name_2' => 'Turcja',
                'matchday_name' => 'Kolejka 1',
                'description' => 'Mistrzostwa Świata',
                'term' => 'niedziela, 14 czerwca',
                'position' => 8,
            ),
            array(
                'meet_name' => 'Mecz 9',
                'team_name_1' => 'Niemcy',
                'team_name_2' => 'Curacao',
                'matchday_name' => 'Kolejka 1',
                'description' => 'Mistrzostwa Świata',
                'term' => 'niedziela, 14 czerwca',
                'position' => 9,
            ),
            array(
                'meet_name' => 'Mecz 10',
                'team_name_1' => 'Holandia',
                'team_name_2' => 'Japonia',
                'matchday_name' => 'Kolejka 1',
                'description' => 'Mistrzostwa Świata',
                'term' => 'niedziela, 14 czerwca',
                'position' => 10,
            ),
            array(
                'meet_name' => 'Mecz 11',
                'team_name_1' => 'Wybrzeże Kości Słoniowej',
                'team_name_2' => 'Ekwador',
                'matchday_name' => 'Kolejka 2',
                'description' => 'Mistrzostwa Świata',
                'term' => 'poniedziałek, 15 czerwca',
                'position' => 11,
            ),
            array(
                'meet_name' => 'Mecz 12',
                'team_name_1' => 'Szwecja',
                'team_name_2' => 'Tunezja',
                'matchday_name' => 'Kolejka 2',
                'description' => 'Mistrzostwa Świata',
                'term' => 'poniedziałek, 15 czerwca',
                'position' => 12,
            ),
            array(
                'meet_name' => 'Mecz 13',
                'team_name_1' => 'Hiszpania',
                'team_name_2' => 'Republika Zielonego Przylądka',
                'matchday_name' => 'Kolejka 2',
                'description' => 'Mistrzostwa Świata',
                'term' => 'poniedziałek, 15 czerwca',
                'position' => 13,
            ),
            array(
                'meet_name' => 'Mecz 14',
                'team_name_1' => 'Belgia',
                'team_name_2' => 'Egipt',
                'matchday_name' => 'Kolejka 2',
                'description' => 'Mistrzostwa Świata',
                'term' => 'poniedziałek, 15 czerwca',
                'position' => 14,
            ),
            array(
                'meet_name' => 'Mecz 15',
                'team_name_1' => 'Arabia Saudyjska',
                'team_name_2' => 'Urugwaj',
                'matchday_name' => 'Kolejka 2',
                'description' => 'Mistrzostwa Świata',
                'term' => 'wtorek, 16 czerwca',
                'position' => 15,
            ),
            array(
                'meet_name' => 'Mecz 16',
                'team_name_1' => 'Iran',
                'team_name_2' => 'Nowa Zelandia',
                'matchday_name' => 'Kolejka 2',
                'description' => 'Mistrzostwa Świata',
                'term' => 'wtorek, 16 czerwca',
                'position' => 16,
            ),
            array(
                'meet_name' => 'Mecz 17',
                'team_name_1' => 'Francja',
                'team_name_2' => 'Senegal',
                'matchday_name' => 'Kolejka 2',
                'description' => 'Mistrzostwa Świata',
                'term' => 'wtorek, 16 czerwca',
                'position' => 17,
            ),
            array(
                'meet_name' => 'Mecz 18',
                'team_name_1' => 'Irak',
                'team_name_2' => 'Norwegia',
                'matchday_name' => 'Kolejka 2',
                'description' => 'Mistrzostwa Świata',
                'term' => 'środa, 17 czerwca',
                'position' => 18,
            ),
            array(
                'meet_name' => 'Mecz 19',
                'team_name_1' => 'Argentyna',
                'team_name_2' => 'Algieria',
                'matchday_name' => 'Kolejka 2',
                'description' => 'Mistrzostwa Świata',
                'term' => 'środa, 17 czerwca',
                'position' => 19,
            ),
            array(
                'meet_name' => 'Mecz 20',
                'team_name_1' => 'Austria',
                'team_name_2' => 'Jordania',
                'matchday_name' => 'Kolejka 2',
                'description' => 'Mistrzostwa Świata',
                'term' => 'środa, 17 czerwca',
                'position' => 20,
            ),
            array(
                'meet_name' => 'Mecz 21',
                'team_name_1' => 'Portugalia',
                'team_name_2' => 'Demokratyczna Republika Konga',
                'matchday_name' => 'Kolejka 2',
                'description' => 'Mistrzostwa Świata',
                'term' => 'środa, 17 czerwca',
                'position' => 21,
            ),
            array(
                'meet_name' => 'Mecz 22',
                'team_name_1' => 'Anglia',
                'team_name_2' => 'Chorwacja',
                'matchday_name' => 'Kolejka 2',
                'description' => 'Mistrzostwa Świata',
                'term' => 'środa, 17 czerwca',
                'position' => 22,
            ),
            array(
                'meet_name' => 'Mecz 23',
                'team_name_1' => 'Ghana',
                'team_name_2' => 'Panama',
                'matchday_name' => 'Kolejka 3',
                'description' => 'Mistrzostwa Świata',
                'term' => 'czwartek, 18 czerwca',
                'position' => 23,
            ),
            array(
                'meet_name' => 'Mecz 24',
                'team_name_1' => 'Uzbekistan',
                'team_name_2' => 'Kolumbia',
                'matchday_name' => 'Kolejka 3',
                'description' => 'Mistrzostwa Świata',
                'term' => 'czwartek, 18 czerwca',
                'position' => 24,
            ),
            array(
                'meet_name' => 'Mecz 25',
                'team_name_1' => 'Czechy',
                'team_name_2' => 'RPA',
                'matchday_name' => 'Kolejka 3',
                'description' => 'Mistrzostwa Świata',
                'term' => 'czwartek, 18 czerwca',
                'position' => 25,
            ),
            array(
                'meet_name' => 'Mecz 26',
                'team_name_1' => 'Szwajcaria',
                'team_name_2' => 'Bośnia i Hercegowina',
                'matchday_name' => 'Kolejka 3',
                'description' => 'Mistrzostwa Świata',
                'term' => 'czwartek, 18 czerwca',
                'position' => 26,
            ),
            array(
                'meet_name' => 'Mecz 27',
                'team_name_1' => 'Kanada',
                'team_name_2' => 'Katar',
                'matchday_name' => 'Kolejka 3',
                'description' => 'Mistrzostwa Świata',
                'term' => 'piątek, 19 czerwca',
                'position' => 27,
            ),
            array(
                'meet_name' => 'Mecz 28',
                'team_name_1' => 'Meksyk',
                'team_name_2' => 'Korea Południowa',
                'matchday_name' => 'Kolejka 3',
                'description' => 'Mistrzostwa Świata',
                'term' => 'piątek, 19 czerwca',
                'position' => 28,
            ),
            array(
                'meet_name' => 'Mecz 29',
                'team_name_1' => 'USA',
                'team_name_2' => 'Australia',
                'matchday_name' => 'Kolejka 3',
                'description' => 'Mistrzostwa Świata',
                'term' => 'piątek, 19 czerwca',
                'position' => 29,
            ),
            array(
                'meet_name' => 'Mecz 30',
                'team_name_1' => 'Szkocja',
                'team_name_2' => 'Maroko',
                'matchday_name' => 'Kolejka 3',
                'description' => 'Mistrzostwa Świata',
                'term' => 'sobota, 20 czerwca',
                'position' => 30,
            ),
            array(
                'meet_name' => 'Mecz 31',
                'team_name_1' => 'Brazylia',
                'team_name_2' => 'Haiti',
                'matchday_name' => 'Kolejka 3',
                'description' => 'Mistrzostwa Świata',
                'term' => 'sobota, 20 czerwca',
                'position' => 31,
            ),
            array(
                'meet_name' => 'Mecz 32',
                'team_name_1' => 'Turcja',
                'team_name_2' => 'Paragwaj',
                'matchday_name' => 'Kolejka 3',
                'description' => 'Mistrzostwa Świata',
                'term' => 'sobota, 20 czerwca',
                'position' => 32,
            ),
            array(
                'meet_name' => 'Mecz 33',
                'team_name_1' => 'Holandia',
                'team_name_2' => 'Szwecja',
                'matchday_name' => 'Kolejka 3',
                'description' => 'Mistrzostwa Świata',
                'term' => 'sobota, 20 czerwca',
                'position' => 33,
            ),
            array(
                'meet_name' => 'Mecz 34',
                'team_name_1' => 'Niemcy',
                'team_name_2' => 'Wybrzeże Kości Słoniowej',
                'matchday_name' => 'Kolejka 4',
                'description' => 'Mistrzostwa Świata',
                'term' => 'sobota, 20 czerwca',
                'position' => 34,
            ),
            array(
                'meet_name' => 'Mecz 35',
                'team_name_1' => 'Ekwador',
                'team_name_2' => 'Curacao',
                'matchday_name' => 'Kolejka 4',
                'description' => 'Mistrzostwa Świata',
                'term' => 'niedziela, 21 czerwca',
                'position' => 35,
            ),
            array(
                'meet_name' => 'Mecz 36',
                'team_name_1' => 'Tunezja',
                'team_name_2' => 'Japonia',
                'matchday_name' => 'Kolejka 4',
                'description' => 'Mistrzostwa Świata',
                'term' => 'niedziela, 21 czerwca',
                'position' => 36,
            ),
            array(
                'meet_name' => 'Mecz 37',
                'team_name_1' => 'Hiszpania',
                'team_name_2' => 'Arabia Saudyjska',
                'matchday_name' => 'Kolejka 4',
                'description' => 'Mistrzostwa Świata',
                'term' => 'niedziela, 21 czerwca',
                'position' => 37,
            ),
            array(
                'meet_name' => 'Mecz 38',
                'team_name_1' => 'Belgia',
                'team_name_2' => 'Iran',
                'matchday_name' => 'Kolejka 4',
                'description' => 'Mistrzostwa Świata',
                'term' => 'niedziela, 21 czerwca',
                'position' => 38,
            ),
            array(
                'meet_name' => 'Mecz 39',
                'team_name_1' => 'Urugwaj',
                'team_name_2' => 'Republika Zielonego Przylądka',
                'matchday_name' => 'Kolejka 4',
                'description' => 'Mistrzostwa Świata',
                'term' => 'poniedziałek, 22 czerwca',
                'position' => 39,
            ),
            array(
                'meet_name' => 'Mecz 40',
                'team_name_1' => 'Nowa Zelandia',
                'team_name_2' => 'Egipt',
                'matchday_name' => 'Kolejka 4',
                'description' => 'Mistrzostwa Świata',
                'term' => 'poniedziałek, 22 czerwca',
                'position' => 40,
            ),
            array(
                'meet_name' => 'Mecz 41',
                'team_name_1' => 'Argentyna',
                'team_name_2' => 'Austria',
                'matchday_name' => 'Kolejka 4',
                'description' => 'Mistrzostwa Świata',
                'term' => 'poniedziałek, 22 czerwca',
                'position' => 41,
            ),
            array(
                'meet_name' => 'Mecz 42',
                'team_name_1' => 'Francja',
                'team_name_2' => 'Irak',
                'matchday_name' => 'Kolejka 4',
                'description' => 'Mistrzostwa Świata',
                'term' => 'poniedziałek, 22 czerwca',
                'position' => 42,
            ),
            array(
                'meet_name' => 'Mecz 43',
                'team_name_1' => 'Norwegia',
                'team_name_2' => 'Senegal',
                'matchday_name' => 'Kolejka 4',
                'description' => 'Mistrzostwa Świata',
                'term' => 'wtorek, 23 czerwca',
                'position' => 43,
            ),
            array(
                'meet_name' => 'Mecz 44',
                'team_name_1' => 'Jordania',
                'team_name_2' => 'Algieria',
                'matchday_name' => 'Kolejka 4',
                'description' => 'Mistrzostwa Świata',
                'term' => 'wtorek, 23 czerwca',
                'position' => 44,
            ),
            array(
                'meet_name' => 'Mecz 45',
                'team_name_1' => 'Szwajcaria',
                'team_name_2' => 'Kanada',
                'matchday_name' => 'Kolejka 5',
                'description' => 'Mistrzostwa Świata',
                'term' => 'środa, 24 czerwca',
                'position' => 45,
            ),
            array(
                'meet_name' => 'Mecz 46',
                'team_name_1' => 'Bośnia i Hercegowina',
                'team_name_2' => 'Katar',
                'matchday_name' => 'Kolejka 5',
                'description' => 'Mistrzostwa Świata',
                'term' => 'środa, 24 czerwca',
                'position' => 46,
            ),
            array(
                'meet_name' => 'Mecz 47',
                'team_name_1' => 'Maroko',
                'team_name_2' => 'Haiti',
                'matchday_name' => 'Kolejka 5',
                'description' => 'Mistrzostwa Świata',
                'term' => 'czwartek, 25 czerwca',
                'position' => 47,
            ),
            array(
                'meet_name' => 'Mecz 48',
                'team_name_1' => 'Szkocja',
                'team_name_2' => 'Brazylia',
                'matchday_name' => 'Kolejka 5',
                'description' => 'Mistrzostwa Świata',
                'term' => 'czwartek, 25 czerwca',
                'position' => 48,
            ),
            array(
                'meet_name' => 'Mecz 49',
                'team_name_1' => 'RPA',
                'team_name_2' => 'Korea Południowa',
                'matchday_name' => 'Kolejka 5',
                'description' => 'Mistrzostwa Świata',
                'term' => 'czwartek, 25 czerwca',
                'position' => 49,
            ),
            array(
                'meet_name' => 'Mecz 50',
                'team_name_1' => 'Czechy',
                'team_name_2' => 'Meksyk',
                'matchday_name' => 'Kolejka 5',
                'description' => 'Mistrzostwa Świata',
                'term' => 'czwartek, 25 czerwca',
                'position' => 50,
            ),
            array(
                'meet_name' => 'Mecz 51',
                'team_name_1' => 'Curacao',
                'team_name_2' => 'Wybrzeże Kości Słoniowej',
                'matchday_name' => 'Kolejka 5',
                'description' => 'Mistrzostwa Świata',
                'term' => 'czwartek, 25 czerwca',
                'position' => 51,
            ),
            array(
                'meet_name' => 'Mecz 52',
                'team_name_1' => 'Ekwador',
                'team_name_2' => 'Niemcy',
                'matchday_name' => 'Kolejka 5',
                'description' => 'Mistrzostwa Świata',
                'term' => 'czwartek, 25 czerwca',
                'position' => 52,
            ),
            array(
                'meet_name' => 'Mecz 53',
                'team_name_1' => 'Japonia',
                'team_name_2' => 'Szwecja',
                'matchday_name' => 'Kolejka 5',
                'description' => 'Mistrzostwa Świata',
                'term' => 'piątek, 26 czerwca',
                'position' => 53,
            ),
            array(
                'meet_name' => 'Mecz 54',
                'team_name_1' => 'Tunezja',
                'team_name_2' => 'Holandia',
                'matchday_name' => 'Kolejka 5',
                'description' => 'Mistrzostwa Świata',
                'term' => 'piątek, 26 czerwca',
                'position' => 54,
            ),
            array(
                'meet_name' => 'Mecz 55',
                'team_name_1' => 'Paragwaj',
                'team_name_2' => 'Australia',
                'matchday_name' => 'Kolejka 6',
                'description' => 'Mistrzostwa Świata',
                'term' => 'piątek, 26 czerwca',
                'position' => 55,
            ),
            array(
                'meet_name' => 'Mecz 56',
                'team_name_1' => 'Turcja',
                'team_name_2' => 'USA',
                'matchday_name' => 'Kolejka 6',
                'description' => 'Mistrzostwa Świata',
                'term' => 'piątek, 26 czerwca',
                'position' => 56,
            ),
            array(
                'meet_name' => 'Mecz 57',
                'team_name_1' => 'Norwegia',
                'team_name_2' => 'Francja',
                'matchday_name' => 'Kolejka 6',
                'description' => 'Mistrzostwa Świata',
                'term' => 'piątek, 26 czerwca',
                'position' => 57,
            ),
            array(
                'meet_name' => 'Mecz 58',
                'team_name_1' => 'Senegal',
                'team_name_2' => 'Irak',
                'matchday_name' => 'Kolejka 6',
                'description' => 'Mistrzostwa Świata',
                'term' => 'piątek, 26 czerwca',
                'position' => 58,
            ),
            array(
                'meet_name' => 'Mecz 59',
                'team_name_1' => 'Republika Zielonego Przylądka',
                'team_name_2' => 'Arabia Saudyjska',
                'matchday_name' => 'Kolejka 6',
                'description' => 'Mistrzostwa Świata',
                'term' => 'sobota, 27 czerwca',
                'position' => 59,
            ),
            array(
                'meet_name' => 'Mecz 60',
                'team_name_1' => 'Urugwaj',
                'team_name_2' => 'Hiszpania',
                'matchday_name' => 'Kolejka 6',
                'description' => 'Mistrzostwa Świata',
                'term' => 'sobota, 27 czerwca',
                'position' => 60,
            ),
            array(
                'meet_name' => 'Mecz 61',
                'team_name_1' => 'Egipt',
                'team_name_2' => 'Iran',
                'matchday_name' => 'Kolejka 6',
                'description' => 'Mistrzostwa Świata',
                'term' => 'sobota, 27 czerwca',
                'position' => 61,
            ),
            array(
                'meet_name' => 'Mecz 62',
                'team_name_1' => 'Nowa Zelandia',
                'team_name_2' => 'Belgia',
                'matchday_name' => 'Kolejka 6',
                'description' => 'Mistrzostwa Świata',
                'term' => 'sobota, 27 czerwca',
                'position' => 62,
            ),
            array(
                'meet_name' => 'Mecz 63',
                'team_name_1' => 'Chorwacja',
                'team_name_2' => 'Ghana',
                'matchday_name' => 'Kolejka 6',
                'description' => 'Mistrzostwa Świata',
                'term' => 'sobota, 27 czerwca',
                'position' => 63,
            ),
            array(
                'meet_name' => 'Mecz 64',
                'team_name_1' => 'Panama',
                'team_name_2' => 'Anglia',
                'matchday_name' => 'Kolejka 6',
                'description' => 'Mistrzostwa Świata',
                'term' => 'sobota, 27 czerwca',
                'position' => 64,
            ),
            array(
                'meet_name' => 'Mecz 65',
                'team_name_1' => 'Demokratyczna Republika Konga',
                'team_name_2' => 'Uzbekistan',
                'matchday_name' => 'Kolejka 6',
                'description' => 'Mistrzostwa Świata',
                'term' => 'niedziela, 28 czerwca',
                'position' => 65,
            ),
            array(
                'meet_name' => 'Mecz 66',
                'team_name_1' => 'Kolumbia',
                'team_name_2' => 'Portugalia',
                'matchday_name' => 'Kolejka 6',
                'description' => 'Mistrzostwa Świata',
                'term' => 'niedziela, 28 czerwca',
                'position' => 66,
            ),
            array(
                'meet_name' => 'Mecz 67',
                'team_name_1' => 'Algieria',
                'team_name_2' => 'Austria',
                'matchday_name' => 'Kolejka 6',
                'description' => 'Mistrzostwa Świata',
                'term' => 'niedziela, 28 czerwca',
                'position' => 67,
            ),
            array(
                'meet_name' => 'Mecz 68',
                'team_name_1' => 'Jordania',
                'team_name_2' => 'Argentyna',
                'matchday_name' => 'Kolejka 6',
                'description' => 'Mistrzostwa Świata',
                'term' => 'niedziela, 28 czerwca',
                'position' => 68,
            ),
            array(
                'meet_name' => 'Mecz 69',
                'team_name_1' => 'Demokratyczna Republika Konga',
                'team_name_2' => 'Uzbekistan',
                'matchday_name' => 'Kolejka 7',
                'description' => 'Mistrzostwa Świata',
                'term' => 'niedziela, 28 czerwca',
                'position' => 69,
            ),
            array(
                'meet_name' => 'Mecz 70',
                'team_name_1' => 'Kolumbia',
                'team_name_2' => 'Portugalia',
                'matchday_name' => 'Kolejka 7',
                'description' => 'Mistrzostwa Świata',
                'term' => 'niedziela, 28 czerwca',
                'position' => 70,
            ),
            array(
                'meet_name' => 'Mecz 71',
                'team_name_1' => 'Algieria',
                'team_name_2' => 'Austria',
                'matchday_name' => 'Kolejka 7',
                'description' => 'Mistrzostwa Świata',
                'term' => 'niedziela, 28 czerwca',
                'position' => 71,
            ),
            array(
                'meet_name' => 'Mecz 72',
                'team_name_1' => 'Jordania',
                'team_name_2' => 'Argentyna',
                'matchday_name' => 'Kolejka 7',
                'description' => 'Mistrzostwa Świata',
                'term' => 'niedziela, 28 czerwca',
                'position' => 72,
            )
        );
        
        $counter = 1;
        $matchdays = 12;
        
//        for($i=1;$i<=$matchdays;$i++){
            foreach ($meetsList as $meetsDetails) {

                $meet = new Meet();
                $meet->setPosition($meetsDetails['position']);
                $meet->setTerm($meetsDetails['term']);
                $meet->setMatchday($this->getReference('matchday-'.$meetsDetails['matchday_name']));
                $meet->setHostTeam($this->getReference('team-'.$meetsDetails['team_name_1']));
                $meet->setGuestTeam($this->getReference('team-'.$meetsDetails['team_name_2']));
                $meet->setName('Mecz '.$counter);
                $meet->setLeague($this->getReference('League-'.$meetsDetails['description']));

                $this->addReference('meet-Mecz '.$counter, $meet);
//                var_dump($counter);
                $manager->persist($meet);
                $counter++;
            }
//        }

            $manager->flush();
        
    }
    
}